apiVersion: v1
kind: Service
metadata:
  name: peer-{{ .PeerName}}
  namespace: {{ .Namespace}}
spec:
  ports:
    - name: tendermint-node
      port: 26657
      targetPort: 26657
    - name: blockchain-api
      port: 1317
      targetPort: 1317
    - name: faucet
      port: 4500
      targetPort: 4500
    - name: p2p
      port: 26656
      targetPort: 26656
  selector:
    app: peer-{{ .PeerName}}
  type: NodePort