
apiVersion: v1
kind: Service
metadata:
  name: peer-persistence-{{ .PeerName}}
  namespace: {{ .Namespace}}
spec:
  ports:
    - name: tendermint-node
      port: 26657
      targetPort: 26657
    - name: blockchain-api
      port: 1317
      targetPort: 1317
    - name: faucet
      port: 4500
      targetPort: 4500
    - name: p2p
      port: 26656
      targetPort: 26656
  selector:
    app: peer-persistence-{{ .PeerName}}
  type: NodePort

---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: {{ .Namespace}}
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5naXRsYWIuY29tIjp7InVzZXJuYW1lIjoiZmlib25hY2NpOTk4IiwicGFzc3dvcmQiOiJBWWVZeVF5V3lDNVduQzQ0clZQVyIsImVtYWlsIjoiZmlib25hY2NpOTk4QGdtYWlsLmNvbSIsImF1dGgiOiJabWxpYjI1aFkyTnBPVGs0T2tGWlpWbDVVWGxYZVVNMVYyNURORFJ5VmxCWCJ9fX0=
type: kubernetes.io/dockerconfigjson
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: env-peer-persistence-{{ .PeerName}}
  namespace: {{ .Namespace}}
data:
  CHAIN_ID: "{{ .ChainId }}"
  MONIKER: "peer-persistence-{{ .PeerName}}"
  PERSISTENCE_PEER_ADDRESS: "{{ .PersistencePeerAddress }}"
  EXTERNAL_ADDRESS: "{{ .ExternalAddress }}"


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: peer-persistence-{{ .PeerName}}
  namespace: {{ .Namespace}}
spec:
  serviceName: peer-persistence-{{ .PeerName}}
  selector:
    matchLabels:
      app: peer-persistence-{{ .PeerName}}
  template:
    metadata:
      labels:
        app: peer-persistence-{{ .PeerName}}
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - command:  
        - /bin/sh 
        - -c
        - |
          #while true; do sleep 30; done;
          FILE=/root/.blog/config/genesis.json;
          if [ ! -f "$FILE" ]; then   
            starport chain init;
            rm /root/.blog/config/genesis.json 
            blogd init $MONIKER --chain-id $CHAIN_ID;
          fi
          CONFIG_FILE=/root/.blog/config/config.toml
          # sed -i "s/\($seeds *= *\).*/\1$PERSISTENCE_PEER_ADDRESS/" $CONFIG_FILE
          sed -i "s/\(external_address *= *\).*/\1$EXTERNAL_ADDRESS/" $CONFIG_FILE
          sed -i "s/\(persistent_peers *= *\).*/\1$PERSISTENCE_PEER_ADDRESS/" $CONFIG_FILE
          sed -i "s/\(seed_mode *= *\).*/\1false/" $CONFIG_FILE
          sed -i "s/\(addr_book_strict *= *\).*/\1false/" $CONFIG_FILE
          blogd start;
        # args: [ "while true; do sleep 30; done;" ]
        image: registry.gitlab.com/akachain/product/akc-landing-page-gitops/cosmos-blog/main_1d85ed6b
        imagePullPolicy: IfNotPresent
        name: peer-persistence-{{ .PeerName}}
        readinessProbe:
          tcpSocket:
            port: 26656
          initialDelaySeconds: 5
          periodSeconds: 10
        envFrom:
        - configMapRef:
            name: env-peer-persistence-{{ .PeerName}}
        volumeMounts:
        - mountPath: /root
          name: peer-persistence-{{ .PeerName}}-pvc

  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: peer-persistence-{{ .PeerName}}-pvc
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
        