apiVersion: v1
kind: Secret
metadata:
  name: regcred
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5naXRsYWIuY29tIjp7InVzZXJuYW1lIjoiZmlib25hY2NpOTk4IiwicGFzc3dvcmQiOiJBWWVZeVF5V3lDNVduQzQ0clZQVyIsImVtYWlsIjoiZmlib25hY2NpOTk4QGdtYWlsLmNvbSIsImF1dGgiOiJabWxpYjI1aFkyTnBPVGs0T2tGWlpWbDVVWGxYZVVNMVYyNURORFJ5VmxCWCJ9fX0=
type: kubernetes.io/dockerconfigjson
