FROM akcadmin/starport:0.18
RUN apt-get install vim telnet -y
WORKDIR /
RUN git clone https://github.com/aura-nw/aura.git
WORKDIR /aura
RUN git reset --hard 1fa6e842e1490a752813c2e6eaebb6cacad2f8ca 
RUN go mod download
RUN make
RUN starport chain init && starport chain build
CMD starport chain serve 
