name: Continuous integration

on:
  push:
    branches: [ main, dev ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set environment variable
      run: |
        SHORT_SHA_COMMIT=$(git rev-parse --short HEAD)
        echo CONTAINER_RELEASE_IMAGE=ghcr.io/aura-nw/vega-test:${GITHUB_REF_NAME}_${SHORT_SHA_COMMIT} >> $GITHUB_ENV
    - name: Build the Docker image and push it to the registry
      env:
        GITHUB_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
        GITHUB_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      run: |
        chmod 777 -R ./ci
        ./ci/build.sh
        ./ci/build-vega-test.sh
    
